CREATE DATABASE IF NOT EXISTS score;
USE score;

CREATE TABLE IF NOT EXISTS score (
id BIGINT NOT NULL AUTO_INCREMENT,
created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
player_name CHAR(20) NOT NULL,
score BIGINT NOT NULL,
PRIMARY KEY (id)
);